### ISSUE TITLE
Crash when given no arguments (OS X 10.10.3, node.js 0.12.2 via brew)

### ISSUE THREAD

**Issue by ear** [kevva/brightness#3]
Hello. I get a crash on my system:

```
$ sw_vers -productVersion 
10.10.3
$ node -v
v0.12.2
```

```
$ npm install -g brightness
/usr/local/bin/brightness -> /usr/local/lib/node_modules/brightness/cli.js
brightness@1.0.0 /usr/local/lib/node_modules/brightness
├── xdg-brightness@2.0.2
├── osx-brightness@3.0.2
└── meow@3.1.0 (object-assign@2.0.0, minimist@1.1.1, camelcase-keys@1.0.0, indent-string@1.2.1)

$ brightness --help

  Change screen brightness

  Example
    $ brightness
    $ brightness 0.8

$ brightness 
/usr/local/lib/node_modules/brightness/node_modules/osx-brightness/index.js:25
		var str = reg.exec(stdout)[0];
		                          ^
TypeError: Cannot read property '0' of null
    at /usr/local/lib/node_modules/brightness/node_modules/osx-brightness/index.js:25:29
    at ChildProcess.exithandler (child_process.js:742:7)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
```

Setting the brightness with `$ brightness <number>` does indeed work.

**Comment by kevva** [comment]
Can you open this at https://github.com/gillstrom/osx-brightness?
