### ISSUE TITLE
catch the errors in cli

### ISSUE THREAD

**Issue by stevemao** [kevva/brightness#5]
https://github.com/gillstrom/osx-brightness/issues/4

I think it should `catch` the errors anyway.

```sh
$ brightness s
/usr/local/lib/node_modules/brightness/node_modules/osx-brightness/index.js:74
		throw new TypeError('Expected a number');
		      ^
TypeError: Expected a number
    at Object.exports.set (/usr/local/lib/node_modules/brightness/node_modules/osx-brightness/index.js:74:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/brightness/cli.js:27:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by kevva** [comment]
Yeah, for this error it makes sense.
